"""rename grade to state

Revision ID: 02db4aae2449
Revises: 
Create Date: 2024-02-03 14:31:20.547616

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "02db4aae2449"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table("article", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "state",
                sa.Enum("READ", "UNREAD", name="state"),
                nullable=False,
                default="UNREAD",
            )
        )
        batch_op.drop_column("grade")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("article", schema=None) as batch_op:
        batch_op.add_column(sa.Column("grade", sa.VARCHAR(length=5), nullable=True))
        batch_op.drop_column("state")

    # ### end Alembic commands ###
