"""add summary_translation

Revision ID: 114bb80448f5
Revises: 02db4aae2449
Create Date: 2024-02-03 15:28:54.735981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '114bb80448f5'
down_revision = '02db4aae2449'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.add_column(sa.Column('summary_translation', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('article', schema=None) as batch_op:
        batch_op.drop_column('summary_translation')

    # ### end Alembic commands ###
